NDKBUILDCMD="/opt/android-ndk-r11c/ndk-build"
NDK_PROJECT_PATH ="/apps/template_android_google/AGK2Template/src/main"
all:
	pwd; $(NDKBUILDCMD) -C $(NDK_PROJECT_PATH) NDK_LIBS_OUT=./jniLibs
clean:
	pwd; $(NDKBUILDCMD) -C $(NDK_PROJECT_PATH) clean
.PHONY: clean
.PHONY: all
